### ISSUE TITLE
Suggesion to add number of posts to retrive

### ISSUE THREAD

**Issue by MallikarjunHt** [genialkartik/react-devdotto#10]
additional parameters like `number of posts`, `pinned posts only`, multiple `card design`. etc

Liked the project i am using in a portfolio check out the [website](https://mallikarjunht.github.io/Portfolio/)

**Comment by genialkartik** [comment]
Thanks, @MallikarjunHt for the suggestion. I'll consider it in the next update.

**Comment by FranciscoMateusVG** [comment]
@MallikarjunHt  and  @genialkartik, made some refactoring and added the possibility to filter `number of posts `  #11

**Comment by genialkartik** [comment]
Thanks, @FranciscoMateusVG for your time and effort.
Will review your PR soon.
