### ISSUE TITLE
Add more Graphics in Documentation 

### ISSUE THREAD

**Issue by chiragkhatri19** [genialkartik/react-devdotto#17]
So this issue is created by me. I'm a Graphics Designing Freelancer and really interested in contributing something valuable to open source this HacktoberFest. So @genialkartik please assign this issue to me. I'm sure I'll create something great.

**Comment by chiragkhatri19** [comment]
Can you give a brief, How you really want the banner/header to be ?

**Comment by chiragkhatri19** [comment]
Or I can freely do it

**Comment by genialkartik** [comment]
Initiate the work with your better understanding. I'll suggest and guide you in between or at the end.

**Comment by chiragkhatri19** [comment]
I just added a Pull Request you can review it

**Comment by genialkartik** [comment]
That was a really appreciative work @chiragkhatri19. Thanks for your contribution.

**Comment by chiragkhatri19** [comment]
> That was a really appreciative work @chiragkhatri19. Thanks for your contribution.

I am really happy that you liked it and this was my first Graphics Contribution.
