### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by genialkartik** [genialkartik/react-devdotto#6]

**Comment by thetayloredman** [comment]
@genialkartik Specifically what do you need done?

**Comment by genialkartik** [comment]
react-devdotto is an NPM module. Now, all I need, Is a well-defined doc and demo of the same!
Other suggestions and PRs are also welcomed!
Happy Coding :)

**Comment by thetayloredman** [comment]
May I reccomend [GitBook](https://gitbook.com/) for docs? It integrates with GitHub and also is hosted with your own `<username>.gitbook.io/<project>` URL. The markdown can be edited directly and it has some stuff added like hints that show as a little warning.
<details>
<summary>The syntax for them is odd, but they can also be added in the editor</summary>

```
{% hint style="info" %}
Hint Syntax example
{% endhint %}
```

</details>

**Comment by thetayloredman** [comment]
*(And this is open source, so I think you can get the paid plan for free?)*

**Comment by genialkartik** [comment]
wow! that's incredibly amazing. I wasn't aware of GitBook.
Thanks for sharing, @thetayloredman 🌟

**Comment by thetayloredman** [comment]
If you want me to help write some initial docs, I can.

**Comment by genialkartik** [comment]
Yeah sure! I can assign you to make docs for this project.

**Comment by thetayloredman** [comment]
Yeah absolutely, It's been a while since I've had to be invited to a gitbook space, so you can probably find it yourself on how to add me :p

**Comment by genialkartik** [comment]
Great! Looking forward to getting it done at best! 👍🏼

**Comment by thetayloredman** [comment]
Alright so are you making a gitbook space or am I making it then transferring?

**Comment by genialkartik** [comment]
I'm not that much familiar with the interface and workflow of GitBook. It'll be better you initiate it and then transfer it.

**Comment by thetayloredman** [comment]
Alright.

**Comment by thetayloredman** [comment]
Ok so I have an invite link, how do you want me to give it to you (it grants admin access)

**Comment by genialkartik** [comment]
mail it on [Gmail](kartik9756@gmai.com)

**Comment by thetayloredman** [comment]
Alright. It's synced to [this repo](https://github.com/thetayloredman/react-devto-docs) and you basically open a "draft" (basically branch) and then save your work (like commits) and then merge it (basically `git merge`)

**Comment by thetayloredman** [comment]
Please remove me from this issue's assignees.
